trigger:
  branches:
    include:
      - '*'
    exclude:
      - main
      - master

resources:
  repositories:
    - repository: templates
      type: github
      name: bcochofel/azuredevops-pipeline-templates
      endpoint: GitHubConnection

stages:
  - stage: pre-commit
    jobs:
      - template: azure-pipelines/tools/pre-commit.yml@templates
