parameters:
  - name: debug
    type: boolean
    default: false

  - name: pool
    type: object
    default:
      vmImage: ubuntu-18.04

trigger: none
pr:
  - '*'

resources:
  repositories:
    - repository: templates
      type: github
      name: bcochofel/azuredevops-pipeline-templates
      endpoint: GitHubConnection

stages:
  - stage: precommit
    jobs:
      - template: azure-pipelines/pre-commit.yml@templates
        parameters:
          pool: ${{ parameters.pool }}
          debug: ${{ parameters.debug }}
