name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

parameters:
  - name: debug
    type: boolean
    default: false

  - name: pool
    type: object
    default:
      vmImage: ubuntu-18.04

trigger:
  branches:
    include:
      - main
      - master
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: bcochofel/azuredevops-pipeline-templates
      endpoint: GitHubConnection

stages:
  - stage: Release
    jobs:
      - template: azure-pipelines/semver-annotated-tag.yml@templates
        parameters:
          pool: ${{ parameters.pool }}
          debug: ${{ parameters.debug }}
